common_issues.md
configuring_project.md
faq_owo.md
index.md
skeleton_auto_config.md
slimevr-setup.md
upload_firmware_guide.md

* Fix typo in word "corresponds"
* Use h1 as heading and title instead of duplicating it
* Move common "To use the ... project" from configuration sections to procedure overview
* "Configuring PlatformIO project" -> "Configuring platformio.ini" since we talk about files now

Review documentation procedures

---

common-issues.md

SlimeVR doesn't need to be launched before SteamVR anymore.
Now tell the user to use the installer to have the right driver and to make sure they have the steamvr slimevr addon enabled in steamvr settings.

Changed Common Issue for trackers not showing up in SteamVR

---

upload-firmware-guide.md

Universal driver seems to no longer contain listed installer executables, but driver for Windows still contains them.

Fix the link to CP210x Windows drivers

---

slimevr-setup.md

The Indicator LEDs turn Blue when finished charging not Green on the now recommended TP4056 charging boards!
I've Verified this with my own TP4056's and others i've found online/in videos and Zrock also confirmed this on their end.

Fixed Minor Mistake, LED on TP4056 turns Blue

---

common-issues.md
configuring-project.md

I have been seeing a few more people having problems connecting their trackers to wifi, and it often ends up being that they have special characters in their SSID (dashes, periods), or are trying to connect to a 5ghz network
Changing the SSID to contain alphanumerical characters only was the last resort fix that ended up working for me.
I would appreciate this being fact-checked though

Elaborate on common wi-fi connectivity issues

---

diy/cases.md

the syntax | in the previous version causes: 
So yeah fixed that.
Only the docs version of MD does that Github preview didn't show it.

Made a small syntax mistake

---

common-issues.md
diy/imu-comparison.md
index.md
server-setup/installing-and-connecting.md

Moved IMU calibration from common issues to the "Test your trackers" section of "Installing the server and connecting your trackers" since this is where people are most likely to find the IMUs seemingly not working, when in reality they just need to be calibrated. Added some clarification regarding what uT ranges are acceptable, and how exactly magnetic environment should be tested (need to walk around playspace). Final changes were minor spelling fixes.

IMU (MPU9250/BMI160) calibration moved, magnetometer clarifications, minor spelling/grammar fixes

---

server-setup/configuring-trackers.md

Previously VRChat only supported 3 additional tracking points aside from headset and controllers, however, it has recently updated to support up to 8 additional tracking points.

VRChat-specific information updated

---

server-setup/setting-reset-bindings.md

Context: TheSkyner#8815 on Discord reported that OVRAS's keybindings don't work if their system language is in Russian but works in English.

Add note for OVRAS' keybindings in other languages

---

diy/components-guide.md

Change wiring recommendation

---

assets/js/configuring-defines.js
common-issues.md
diy/components-guide.md
firmware/configuring-project.md
firmware/upload-firmware.md

Added the long since missing, "battery level pin guide", added an option for "None" to the defines.h generator for aux IMUs, and added an additional section to the common issues page regarding why a tracker might be able to connect and yet not show up in the SlimeVR server.

Defines.h Settings Clarification, and Additional Common Issue

---

firmware/upload-firmware.md

This is something I ran into with my trackers, and NWB believes that they were affected by this too.
Turning the tracker off *right* after an OTA, even if it says "Update Success" in VS Code, will temporarily brick the tracker until you re-flash it over USB. After the upload, the ESP processes (likely checksumming) the update, and then reboots into the new firmware. During that processing is when I, and likely others, have temporarily borked ourselves.

Add warning about incomplete OTAs.

---

book.toml

- Redirects all index pages to the appropriate `index.html` pages
- Redirects all `server-setup` pages to `server`

Add Jekyll page redirects

---

src/firmware/README.md

recently trying to DIY IMU Tracker, found out the link is not working
Ref: https://docs.slimevr.dev/firmware/index.html

fix: firmware url link

---

src/diy/components-guide.md
src/diy/imu-comparison.md
src/misc/survey.md

- Added note to TP4056 section to pair charging board with a 1000mAh or greater battery.
- Added note that JST connectors are optional
- Removed note about difficulty to obtain BNO085s
- Updated IMU ratings and reset times
- Ordered IMUs, best to worst, noting that BMI160 is the over all best price-to-performance IMU

Updated Components Guide, and IMU Comparison

---

src/diy/cases.md

the Minted Arcturus link for thingverse was redirecting to a 404 page

Fixed a broken link in cases.md docs

---

.github/workflows/publish.yml
README.md

I've moved the code to its own repository and publised a crate on crates.io to make it easier to reuse.

Use stand-alone mdbook-i18n-helpers crate

---

src/tools/shadowpc.md

Summary:
The ShadowPC client recently implemented filtering to what types of USB devices are allowed to be forwarded with the official client and now no longer allows forwarding of Network Cards. This updates the documentation to more closely reflect the actual usage the original user used when they used the ShadowPC with their DIY Slimes. It now uses the Virtual Here exclusively in the documentation since based on other Discord user troubleshooting that method remains operational like it was when originally using this approach to enjoy SlimeVR on a ShadowPC.

chore: update ShadowPC Documentation

---

po/en/messages.pot
po/es-419/messages.po
src/common-issues.md
src/firmware/configuring-project.md
src/firmware/setup-and-install.md
src/firmware/upload-firmware.md

Should be kept the same as before inside link and code (doesn't actually matter for links but it looks better

Actually capitalised PlatformIO correctly

---

src/tools/linux-installation.md

I would like someone else to verify this behavior, but I don't seem to be able to download the artifacts specified in this guide unless I am logged into my GitHub account. When I am logged out / in incognito mode, they display the names of the artifacts without any links.

Note that GitHub account needed to download build artifacts

---

src/tools/linux-installation.md

Followup to [PR 215](https://github.com/SlimeVR/SlimeVR-Docs-Site/pull/215).
- I updated instructions to use the AppImage from the latest release (much simpler to use)
- I added a small section on firewall rules in Linux
- I moved all previous instructions to a "Legacy Setup" section for now. Should this be removed entirely?

Rewrite linux installation guide

---

src/server/body-config.md

This updates pretty much all the AutoBone information, but to summarize:
- The "reset proportions" step optional now as the height is set by the GUI, so it doesn't need to rely on existing body proportions.
- The wording for the requirements at the start has been updated to be more clear and really push that you need to have your tracking working BEFORE using AutoBone (as if anyone reads it anyways -w-).
- All the configs have been updated to reflect the current version now.
- Removed a really old note about v0.6.3, which nobody should be using anymore anyways lol.

Update AutoBone information, steps, and config

---

src/assets/js/configuring-defines.js

Updated based on https://github.com/SlimeVR/SlimeVR-Tracker-ESP/blob/main/src/defines.h.
BNOs wouldn't work with the v0.4.0 firmware release with the current generated defines file. This updates it so it should work.

Update defines generator

---

src/diy/components-guide.md

I think this makes more sense for D1 minis. They're usually referred to by their port or version, not their UART chipset, at least by most sellers on AliExpress. And there's no real info on fake FT232 chips (they work fine), it's only the CH340s that are counterfeit

Updated info on D1 mini

---

src/diy/diy_kit_guide.md

Fixed Official PCB Case for 3D Printer Link in DIY Kit Guide.

Fixed Official PCB Case for 3D Printer Link

---

src/tools/README.md

Fixes SlimeTora leading to a 404 on the main `tools` page
(my bad)

Fix 404 link

---

src/diy/imu-comparison.md
src/firmware/setup-and-install.md
src/server/imu-calibration.md

Not needed since https://github.com/SlimeVR/SlimeVR-Tracker-ESP/pull/322 got merged

Remove warning about custom firmware for BMI270

---

src/server/imu-calibration.md

I clarified that other imus like bmi270 or lsm need 6 side too, and i removed the setting down part being specific to bno or mpu, since every other imu i know of benefits from it as well.

update calibration instructions to include sfusion imus

---

src/common-issues.md
src/tools/owoTrack.md

- Quest Pro controllers use WiFi and can commonly interfere with 2.4 GHz WiFi that SlimeVR uses
- Modified OSes sometimes mess with the network settings and you need to just run that command and it'll fix it right up
- owoTrack tells you to install Oracle Java 8 for run.bat, what frickin' year is it??? 💀

Add Quest Pro help, netsh help, and update owoTrack info

---

src/tools/owoTrack.md

Basically just adds in the fact that iPhone also needs the app to have the permission to **communicate on local networks** without that, no matter what you do, the app won't connect to slimevr

Add a potential fix for iPhone

---

src/assets/js/configuring-defines.js

Just a code comment that was a bit back to front.
MPUs require USE_6_AXIS to be false, not true.

Fixed inverted boolean in comment

---

src/assets/js/diy.js

Just a typo fix to make the Adafruit BNO085 link visible again in the cost calculator

Fix malformed HTML in BNO085 link

---

src/SUMMARY.md
src/glossary.md

Super cool SlimeVR glossary that provides base definitions for most SlimeVR related terms with some relevant info, like misconceptions and where to find more information regarding a specific term. This is meant to be brief, direct, and low maintenance. Further explanation and description of terms can be done on their relevant sections in the docs and can be linked where appropriate.
This glossary should be really helpful for newcomers to the SlimeVR space, where they have no idea what a "SlimeVR server" or "Yaw reset" is.

SlimeVR terminology page

---

src/slimevr101.css

Now:
With this change:
(Difference in colors comes from different themes used on different screenshots)

Made small resolution cards display cells inline

---

src/common-issues.md

added a reminder to ensure that the cabel is fully inserted and clicked into place, as while it may supply power it might not supply data without full insertion.
I have had this occur twice when assisting people with troubleshooting and ran it by @Smeltie with wording.

Added a cable insertion reminder

---

src/diy/smol-slimes/smol-flashing-firmware.md

1. Adds hint about using the Serial Console for putting a device into DFU mode. Useful when updating eByte dongle for example, as the button is normally inaccessible
2. No longer assumes that self-built firmware is used

smol-flashing-firmware.md: Add note for DFU mode via Serial, Link to pre-compiled firmware

---

src/smol-slimes/assets/js/smol-building-calculator.js
src/smol-slimes/hardware/smol-diy-set-cost-calculator.md
src/smol-slimes/hardware/smol-slimes-community-builds.md
src/smol-slimes/hardware/smol-slimes-community-straps.md

Updated smol set calculator to list options as radio cards and not just radio buttons. Added next steps under calculator.
