- upload_firmware_guide.md
Fixed a couple typos and added credit to Eiren.
> Update firmware guide

- index.md
Waiting on this change to be approved before adding to all other pages so I don't have to do more work if something needs to be changed
> Added rudimentary navigation buttons

- _sass/custom/custom.scss
- common_issues.md
- skeleton_auto_config.md
Added video, styling for video for graceful resizing, changed meters to cm on the auto skeleton page and wrote up a common issues page based on the #technical-support channel
> Auto Skeleton video and wording update, common issues page

- _sass/custom/custom.scss
- common_issues.md
- defines_guide.md
- faq_owo.md
- index.md
- platformio-guide.md
- skeleton_auto_config.md
- slimevr-setup.md
- upload_firmware_guide.md
Hi guys, I've noticed this project and decided to contribute to the docs :) If you find this commit too large and hard to review, I can try splitting it on separate PRs to simplify review process. And thanks for the great project!
* Fix typos
* Correct the documentation styling
* Fix links to `.md` files
* Use title case capitalization in headings
* Remove punctuation characters from headings
* Add missing punctuation characters in lists, paragraphs, etc.
* Use auto-numbering for markdown lists
* Remove unnecessary empty lines
* Add C language identifier to code blocks in `defines_guide.md`
* Use consistent naming of owoTrack app
* Improve guide section names
* Improve wording of some procedures and steps
> Documentation improvements

- _sass/custom/custom.scss
- common_issues.md
- skeleton_auto_config.md
- slimevr-setup.md
- upload_firmware_guide.md
Ok this one is good, sorry about the cancelled requests
> Fixes to layouts, LED Blinking lights, common issues and firewall suggestions

- common_issues.md
- slimevr-setup.md
- upload_firmware_guide.md
Too many people have been using Null Floof's video, removed the link entirely (left in the thank you since the image helps)
> Minor changes to common issues, removed Null Floof link, added readability, calibration process added

- configuring-project.md
- slimevr-setup.md
- upload-firmware-guide.md
* Mention owoTrack devices in Connect trackers section of slimevr-setup.md
* Update `defines.h` image and related fields in upload-firmware-guide.md
* Improve wording configuring-project.md
* Improve wording in upload-firmware-guide.md
> Revise the docs

- assets/js/configuring-defines.js
These changes are to bring in line the docs to the changes made in https://github.com/SlimeVR/SlimeVR-Tracker-ESP/pull/38 and https://github.com/SlimeVR/SlimeVR-Tracker-ESP/pull/40 .
Also removed the INT pin definitions if using a non-BNO IMU.
> Changed I²c speed to 400k. Added warning about MPU9250. Removed INT pins for non-BNO's

- slimevr-setup.md
- No one puts chest on side. It’s just bad
- Added recommendation for hip tracker
> Update mounting position recommendations

- assets/js/diy.js
> More update on BNO prices

- components-guide.md
> Update BNO price

- body-config.md
- slimevr-setup.md
- Changed manual configuration of body proportions.
- Added instructions on which SteamVR to enable.
- Copied straight from the discord #calibration channel.
> Calibration fox changes

- server-setup/body-config.md
my neck length is 13, so I think 8 to 14 would be better.
> updated neck sensible/recommended values

- diy/cases.md
Added a few missing bullet points to the Hyperion section.
> Added bullet points for hyperion

- diy/diy-trackers-guide.md
Embed link incorrect should be fixed now.
> Update to video link

- server-setup/body-config.md
- server-setup/configuring-trackers.md
- slimevr101.md
TODO:
- Component lists page
- Body proportion image (with purple person)
> Some elbow tracking info

- diy/imu-comparison.md
Just 2 minor fixes that worked but due to an earlier change no longer worked right.
These are now fixed.
> Minor Finishing touches that didn't translate well beforehand

- server-setup/body-config.md
Too many people tried Autobone without the HMD...
> specify headset must be on for autobone

- diy/IMU-Performance.md
Preview: https://deiteris.github.io/SlimeVR-Docs-Site/diy/IMU-Performance.html
> Separate content with blank lines in IMU-Performance.md

- diy/imu-comparison.md
Hopefully this will better cover some the faqs on the ICM-20948.
> Updated ICM-20948 to cover some faqs.

- server-setup/configuring-trackers.md
- server-setup/putting-on-trackers.md
- tools/owoTrack.md
Rename ankles to lower legs, knees to upper legs, and other adjustments.
> fix for new server version

- diy/imu-comparison.md
post-build-survey.md -> /slimevr-experience-survey.md
> Fix survey link

- common-issues.md
- server-setup/body-config.md
- server-setup/configuring-trackers.md
- server-setup/putting-on-trackers.md
(my website: https://louka3000.github.io/SlimeVR-Calibration)
Adding all the relevant information from my website to the docs.
note: I removed the " ### Set tracker roles in SteamVR" section, as the user does not need to do this, because SlimeVR now automatically does it reliably.
> Calibration info

- assets/js/configuring-defines.js
- assets/js/schematics.js
Some minor js changes to make it more readable. Tested locally.
> Schematics code cleanup

- server-setup/body-config.md
- Updates the documentation for AutoBone config and terminology
- Updates the locations for recordings
- Adds a "Debugging" section to help with people having problems using AutoBone
> Update AutoBone documentation and add debug section

- server-setup/body-config.md
Fixed grammar
Edited for clarity
Slight reorder of sections to improve UX
lots of changes found here https://docs.google.com/document/d/17I6t0GxVZSNwgBiOk7YglwMN1psjY-5n-tRIg7ib03M/edit
> body-config - Editing pass

- tools/termux-installation.md
I didn’t realize that would be the document name on the site…
> Change “What is this?” to Termux Setup

- server-setup/osc-information.md
- tools/termux-installation.md
Fix some wording, formatting and details on resetting in/before being in VRChat.
> Fix some osc docs stuff

- tools/termux-installation.md
to be able to have a beta version of the site, gotta make people know that it shouldn’t be using beta if they don’t want beta
> Remove Beta

- tools/termux-installation.md
Converted the installer to an auto updating one, and now you can start it with a simple ./start.sh
Need to change the docs to reflect the changes to the installer.
> Auto-Update Setup

- diy/imu-comparison.md
Updated BMI160 in imu comparison to better reflect the current situation, and make it seem more favorable over the MPU6050/00, as it is. Also added the calibration on each startup as a negative on the MPU's
> Updated BMI160 in imu comparison

- server-setup/osc-information.md
OSC is no longer in VRChat Beta, and added info about OSC Debug option
> OSC Information Update

- safety-guides.md
- safety/de/safety.ftl
- safety/en/safety.ftl
- safety/es/safety.ftl
- safety/fr/safety.ftl
- safety/jp/safety.ftl
- safety/ko/safety.ftl
- safety/nl/safety.ftl
First off IDK if I did this right.
The goal of this PR is to add a page to the documentation website with the safety information, open to suggestions on how this specifically should be achieved. For now I added them all on a single page as a template/first suggestion.
> Adding Safety Guide

- .github/workflows/publish.yml
> Fix action

- src/README.md
> fix: shipping date

- src/diy/cases.md
Typo with my name, and added a line to space out authors
> Typo with custom case

- src/misc/survey.md
Given the number of old results potentially tainting the results of the survey, it is probably for the best that the survey be periodically be reset.
The results of the survey can still be accessed at the old link. If anyone wants the old results shared with them, message me on Discord (NWB#5135)
> Updated Survey (Cleared Previous Results)

- src/diy/cases.md
Improper link for minted arcturus
> Fixed link I think?

- src/server/body-config.md
People have asked about this, it would be nice to have :3
> Add requirements to AutoBone instructions

- src/diy/cases.md
The new design of my pcbs/cases support mpu6050s, bmis160s, and BNO085s all on one pcb! Thanks guys! :D
> Added the new version of my Frozen Slime cases. 

- src/common-issues.md
> Add gui tiny window in common issues

- src/server/putting-on-trackers.md
> remove Eiren pics for mounting

- src/common-issues.md
> Update common issues up to date

- src/assets/js/configuring-defines.js
> fix-defines.h

- src/tools/lime-slimes.md
Link to current BETA in discord
> Marking current L,i,me as OUTDATED, Linked BETA as most current

- src/assets/js/diy.js
- src/common-issues.md
WiFi Channels:
Channels 12-14 may run into connection issues with ESP8266/ESP32.
https://www.hackster.io/news/esp8266-or-esp32-connectivity-woes-check-your-wi-fi-channel-suggests-olimex-s-tsvetan-usunov-d6d4791884d3
https://olimex.wordpress.com/2021/12/10/avoid-wifi-channel-12-13-14-when-working-with-esp-devices/
Straps:
Previous alt (Amazon) straps were too short for anything other than ankles/elbows for the Components Guide.
> Updating docs

- src/diy/cases.md
- src/diy/imu-comparison.md
- src/diy_kit_guide.md
Added links to main cases and bno modules in relevant sections, also made small adjustments to the imu comparison page
> Added webstore links to relevant locations and small fixes

- src/diy/cases.md
- src/diy/components-guide.md
- src/diy/imu-comparison.md
- src/diy_kit_guide.md
Mostly adding periods, fixing styling, adding links to the store, added a youtube video to DIY kit section.
> Small changes

- src/common-issues.md
This provides a single location to find everything you need to know about serial connections issues and drivers. This should make DIY easier as currently this information is spread out between pins on the Discord.
> Add a section for serial issues to common issues

- book.toml
- src/README.md
- src/diy/README.md
Fixes DIY kit guide links and adds a redirect so any old links will go to the correct location.
Fixes #242
> Fix DIY kit guide links & add redirect

- src/server/initial-setup.md
Some people in the DIY channel on Discord were asking for temp calibration instructions to be included in the docs, so I wrote them
> Add BMI160 temperature calibration instructions

- src/server/body-config.md
This was changed in v0.9.0, the docs should be updated
> Update AutoBone recording location

- po/en/messages.pot
- src/SUMMARY.md
- src/common-issues.md
- src/diy/imu-comparison.md
- src/server/README.md
- src/server/imu-calibration.md
- src/server/initial-setup.md
This PR is based off a message in the SlimeVR Discord at https://discord.com/channels/817184208525983775/930204651586981918/1193597140019183706.
For convenience, I did the move and the cleanup on separate commits so the changes to the IMU calibration can be reviewed more easily.
> Move IMU calibration to its own page and clean it up

- src/diy/cases.md
Very smol PR, just fixes the link to the Minted Arcturus case since it's not on Thingiverse anymore.
> Fix link to Minted Arcturus case

- src/quick-setup.md
Fix 404 hyperlink inside setup docs
> Fix URL redirect in quick setup page

- src/tools/vrchat-config.md
Been told it doesn't show how recommended it is for new users by saying "Optional", so the recommended ones for new users now say "Recommended".
> Recommend settings on VRChat config

- src/updating-firmware.md
Correcting missing letter 'S' in the word 'Shorting'
> Grammar correction

- src/diy/imu-comparison.md
I forgot to update it there in #273 oopsie
> Fix BMI270 price in imu-comparison

- src/misc/contributors.md
- src/tools/slimetora.md
Updated the SlimeTora documentation page since there has been a few changes from v1.1.0
> Update SlimeTora docs page

- src/server/body-config.md
- src/tools/mobile-installation.md
- src/tools/termux-installation.md
The debug steps provided are old and irrelevant, so this updates them to represent the current state of things. Also I added a recommendation not to use the Quest for standalone 'cause it just sucks lol. Annnd lastly adding a warning about using Termux 'cause pls stop.
> Update AutoBone info & add mobile recommendation

- src/assets/js/diy.js
- src/assets/js/schematics.js
- src/diy/imu-comparison.md
- src/diy/tracker-schematics.md
Updating IMU comparison and schematics to include 3 LSM6DSO, LSM6DSV and LCM-45686. also updated alot of outdated info on the schematics and IMU comparison section.
> Updating IMU comparison and schematics

- .github/workflows/publish.yml
Fix issue on Github Actions failed to build/deploy after my last PR merged. Smol Slime Update (#317)
> Update Page Deployment Dependencies

- src/server/osc-information.md
VRChat -> VRChat OSC Trackers and added a screenshot so people are less confused.
> Edited for clarity. Added a screenshot.

- src/diy/smol-slime.md
Added Panini GitHub, author and battery details to the Hardware section at the bottom of Smol_slime.md
Additionally fixed some syntax layouts that were irking me but had no real effect on the final product
> Added Panini Smols to Smol_Slime.md and syntax

- src/updating-firmware.md
Just a small hotfix to make the steps more clear.
> Small hotfix

- src/updating-firmware.md
Just a small fix to the flashing page changing the type of screwdriver we recommend.
> Update to required screwdriver type

- src/tools/MacOS-Installation.md
> Adding credit to MacOS Install

- src/common-issues.md
Fixed an issue where the images would not load due to the link being incorrect for web usage (worked in the code editor)
> Fixed image links as they would not load, my bad.

- src/diy/smol-slimes/smol-slimes-community-builds.md
- src/diy/smol-slimes/smol-slimes.css
Styles to display smols comminity builds table on mobile as list of sortable cards.
> Styles to display smols comminity builds table on mobile as list of sortable cards.

- src/common-issues.md
Added common fixes for Searching for server issue. Im not sure if i did the formatting correctly so please double check <3 
(I linked to the page and im assuming thats OK but not best practice cuz i dunno how to do an anchoring link or watevers T_T)
> Update common-issues.md. Added common fixes for Searching for server issue.

- src/common-issues.md
> Fixed a missing period of the end of a sentence

- src/smol-slimes/assets/js/smol-building-calculator.js
- src/smol-slimes/firmware/smol-compiling-firmware.md
- src/smol-slimes/firmware/smol-flashing-firmware.md
- src/smol-slimes/firmware/smol-pre-compiled-firmware.md
- src/smol-slimes/hardware/smol-receiver.md
- src/smol-slimes/hardware/smol-tracker.md
Once merged, I will update CI with proper pre-compiled firmware filenames, so links work.
> Renamed Board SuperMini to ProMicro

- src/slimevr101.md
The imu numbers were inconsistend, we never use it like that anywhere else and its pretty confusing
> Make tracker numbers consistent again in slimevr101

- src/assets/js/diy.js
- src/smol-slimes/assets/js/smol-building-calculator.js
- src/smol-slimes/hardware/smol-tracker.md
Deyta is selling LSM6DSR now. Will update ICM-45686 when SlimeVR Store has them in stock.
> Deyta's LSM6DSR Page

- src/tools/linux-installation.md
**Issue:** https://github.com/SlimeVR/SlimeVR-Docs-Site/issues/412
**Source:** https://github.com/SlimeVR/SlimeVR-Server/blob/069da63d1f77b9e31d495dacbfb5974f4596543a/server/core/resources/firewall.bat#L26-L28
> Add OTA Port to Linux Firewall Section

- src/smol-slimes/assets/js/smol-building-calculator.js
Strap cost on calculator is correct for 5m.
> Smol Calc and Doc Qty Inconsistency 

- theme/index.hbs
Small fix for plausible so the actual doc domain show on the interface
> Update domain set
